name: Reusable Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal --logger trx --results-directory ${{ github.workspace }}/TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: ${{ github.workspace }}/TestResults/
          if-no-files-found: ignore
          retention-days: 3

